import { Poppins as PoppinsFont } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";

const poppins = PoppinsFont({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Gois Blog",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>{children}</body>
      <Footer />
    </html>
  );
}
